### ISSUE TITLE
Way to generate category labels  for CenterPose ?

### ISSUE THREAD

**Issue by ArghyaChatterjee** [NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation#15]
Hello,

Thanks for your work. Is there a way to generate category labels in CenterPose as you do for DOPE during instance segmentation ? As there can be multiple categories, it's confusing if the network is not generating any labels for each category.

Thanks in advance.

**Comment by jaiveersinghNV** [comment]
The CenterPose model architecture requires each individual model to be trained on a specific category of object. As a result, the Isaac ROS CenterPose Node doesn't provide any category labels for its outputs; any output by the network is necessarily an object of the class that this particular network was trained on.

For example, when running the CenterPose Node following our tutorial [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation/blob/main/docs/centerpose.md), the node will only output poses of shoes, since the default model used is the [`shoe_resnet_140.pth`](https://drive.google.com/drive/folders/1QIxcfKepOR4aktOz62p3Qag0Fhm0LVa0).

If you wish to run multiple instances of CenterPose node, each using a different model to detect a different category of objects, then you can use the ROS 2 topic remapping functionality to separate the topic outputs at a graph level.
